### ISSUE TITLE
请求异常问题

### ISSUE THREAD

**Issue by cways** [zj-depart2/zjmuidp#7]
![image](https://cloud.githubusercontent.com/assets/6712443/23778915/290ade82-0578-11e7-814f-457da8b2c1e4.png)
进入设计器页面时，请求图片报异常
@liangzhanyong @tinybull

**Comment by cways** [comment]
* 获取List<image>的接口为：/image/list

**Comment by tinybull** [comment]
我将请求的路径改为
![image](https://cloud.githubusercontent.com/assets/8937302/23883952/e8c32dae-08a4-11e7-89b2-8e5db87e5b1b.png)
![image](https://cloud.githubusercontent.com/assets/8937302/23884089/9cc8270a-08a5-11e7-98df-705cbf3ca186.png)
但是还是报错 @cways

**Comment by liangzhanyong** [comment]
因为后台查询时没有找到/images文件夹导致
